# Dataset config file.
output_dir = '/output'
dataset = '/configs/dataset.toml'

# Training settings
epochs = 500
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 1
gradient_clipping = 1.0
warmup_steps = 100

# eval settings
eval_every_n_epochs = 1
eval_before_first_step = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

# misc settings
save_every_n_epochs = 10
checkpoint_every_n_epochs = 10
activation_checkpointing = true
partition_method = 'parameters'
save_dtype = 'bfloat16'
caching_batch_size = 1
steps_per_print = 1
video_clip_mode = 'single_middle'

[model]
type = 'hunyuan-video'
transformer_path = '/models/hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors'
vae_path = '/models/hunyuan_video_vae_bf16.safetensors'
llm_path = '/models/llm'
clip_path = '/models/clip'
dtype = 'bfloat16'
transformer_dtype = 'float8'
timestep_sample_method = 'logit_normal'

[adapter]
type = 'lora'
rank = 16
dtype = 'bfloat16'
#init_from_existing = '/configs'

[optimizer]
type = 'adamw_optimi'
lr = 2e-5
betas = [0.9, 0.99]
weight_decay = 0.02
eps = 1e-8